MyBlog/MyBlog.WebUI/Models/BlogListViewModel.cs
using MyBlog.Entities.Concrete;

namespace MyBlog.WebUI.Models
{
    public class PageInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public string CurrentCategory { get; set; }

        public int TotalPages()
        {
            return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
        }
    }
    public class BlogListViewModel
    {
        public PageInfo PageInfo { get; set; }
        public List<Blog> Blogs { get; set; }
    }
}

MyBlog/MyBlog.WebUI/ViewComponents/Admin/AdminBlogListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;

namespace MyBlog.WebUI.ViewComponents.Admin
{
    public class AdminBlogListViewComponent:ViewComponent
    {
        private IBlogService _blogService;
        public AdminBlogListViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public IViewComponentResult Invoke()
        {
            var values = _blogService.GetAll();
            return View(values);
        }
    }
}

MyBlog/MyBlog.WebUI/ViewComponents/Admin/BlogCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;

namespace MyBlog.WebUI.ViewComponents.Admin
{
    public class BlogCountViewComponent : ViewComponent
    {
        private IBlogService _blogService;
        public BlogCountViewComponent(IBlogService blogService)
        {
            _blogService = blogService;
        }
        public IViewComponentResult Invoke()
        {
            var values = _blogService.GetAll();
            return View(values);
        }
    }
}

MyBlog/MyBlog.WebUI/ViewComponents/Admin/CategoryCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;

namespace MyBlog.WebUI.ViewComponents.Admin
{
    public class CategoryCountViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public CategoryCountViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            var entity = _categoryService.GetAll();
            return View(entity);
        }
    }
}

MyBlog/MyBlog.WebUI/ViewComponents/Admin/MessageCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;

namespace MyBlog.WebUI.ViewComponents.Admin
{
    public class MessageCountViewComponent : ViewComponent
    {
        private IMessagesService _MessagesService;
        public MessageCountViewComponent(IMessagesService MessagesService)
        {
            _MessagesService = MessagesService;
        }
        public IViewComponentResult Invoke()
        {
            var values = _MessagesService.GetAll();
            return View(values);
        }
    }
}

MyBlog/MyBlog.WebUI/Views/Admin/BlogAdd.cshtml
@using MyBlog.Entities.Concrete;
@using MyBlogWebUI.Models;
@model BlogModel
@{
    ViewData["Title"] = "Blog Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    DateTime bugun = DateTime.Today;
}
<form asp-controller="Admin" asp-action="BlogAdd" method="post" class="forms-sample form-check" enctype="multipart/form-data">
    <div class="row">
        <div class="col-8 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Blog Ekle</h4>

                    <div class="form-group">
                        <label>Blog Başlık</label>
                        <input asp-for=Title type="text" class="form-control" placeholder="Blog Başlık">
                    </div>
                    <div class="form-group">
                        <label>Blog Url</label>
                        <input asp-for=Url type="text" class="form-control" placeholder="Kategori Url">
                    </div>
                    <div class="form-group">
                        <label>Kısa Açıklama</label>
                        <input asp-for=Description type="text" class="form-control" placeholder="Kısa Açıklama">
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        <textarea asp-for=Content class="form-control" id="editor" placeholder="Açıklama" style="height:200"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Resim Url</label>
                        <input type="hidden" asp-for="ImgUrl" width="100" />
                        <input type="file" name="file" />
                    </div>
                    <div class="form-group">
                        <label>Puan</label>
                        <input asp-for=Puan type="text" class="form-control" placeholder="Puan">
                    </div>
                    <div class="form-group">
                        <label>Yayınlama Tarihi</label>
                        <input asp-for=CreateDate value="@bugun" type="text" class="form-control" placeholder="Puan">
                    </div>
                    <div class="form-group">
                        <label>Yazar</label>
                        @Html.DropDownListFor(x=>x.AuthorId,(List<SelectListItem>)ViewBag.au,new{@class="form-control"})
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-gradient-warning mr-2">Kaydet</button>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-4 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Kategori</h4>
                    @foreach (var item in Model.selectedCategories)
                    {
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input type="checkbox"
                                       class="form-check-input"
                                       name="categoryIds"
                                       value="@item.Id"
                                       id="category_@(item.Id)">
                                    @item.CategoryName
                                </label>
                            </div>
                        </div>
                    }
                    <hr />
                    <h4 class="card-title">Blog Durum</h4>
                    <div class="form-group">
                        <div class="form-check">
                            <label asp-for="Isapproved" class="form-check-label">
                                <input asp-for=Isapproved type="checkbox" class="form-check-input">Yayınla
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
@section Scripts
    {
    <script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('editor');
    </script>
    }

MyBlog/MyBlog.WebUI/Views/Admin/BlogEdit.cshtml
@using MyBlog.Entities.Concrete;
@using MyBlogWebUI.Models;
@model BlogModel
@{
    ViewData["Title"] = "Blog Düzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    DateTime bugun = DateTime.Today;
}
<form asp-controller="Admin" asp-action="BlogEdit" method="post" class="forms-sample form-check" enctype="multipart/form-data">
    <div class="row">
        <div class="col-8 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Blog Düzenle</h4>
                    <div class="form-group">
                        <label>Blog Başlık</label>
                        <input name="Id" type="text" readonly value="@Model.Id" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Blog Başlık</label>
                        <input asp-for=Title type="text" class="form-control" placeholder="Blog Başlık">
                    </div>
                    <div class="form-group">
                        <label>Blog Url</label>
                        <input asp-for=Url type="text" class="form-control" placeholder="Kategori Url">
                    </div>
                    <div class="form-group">
                        <label>Kısa Açıklama</label>
                        <input asp-for=Description type="text" class="form-control" placeholder="Kısa Açıklama">
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        <textarea asp-for=Content id="editor" class="form-control" placeholder="Açıklama" style="height:200"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Resim Url</label>
                        <input type="hidden" asp-for="ImgUrl" />
                        <img src="~/img/@Model.ImgUrl" width="100" />
                        <input type="file" name="file" />
                    </div>
                    <div class="form-group">
                        <label>Puan</label>
                        <input asp-for=Puan type="text" class="form-control" placeholder="Puan">
                    </div>
                    <div class="form-group">
                        <label>Yayınlama Tarihi</label>
                        <input asp-for=CreateDate value="@bugun" type="text" class="form-control" placeholder="Puan">
                    </div>
                    <div class="form-group">
                        <label>Yazar</label>
                        @Html.DropDownListFor(x=>x.AuthorId,(List<SelectListItem>)ViewBag.au,new{@class="form-control"})
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-gradient-primary mr-2">Blog Kaydet</button>
                    </div>

                </div>
            </div>
        </div>


        <div class="col-4 grid-margin stretch-card">

            @for (int i = 0; i < Model.selectedCategories.Count; i++)
            {
                <input type="hidden" name="selectedCategories[@i].Id" value="@Model.selectedCategories[@i].Id">
                <input type="hidden" name="selectedCategories[@i].CategoryName" value="@Model.selectedCategories[@i].CategoryName">
            }

            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Kategori</h4>
                    @foreach (var item in (List<Category>)ViewBag.Categories)
                    {
                        <div class="form-group">
                            <div class="form-check">
                                <label class="form-check-label" for="category_@(item.Id)">
                                    <input type="checkbox"
                                       class="form-check-input"
                                       name="categoryIds"
                                       value="@item.Id"
                                       id="category_@(item.Id)"
                                       @(Model.selectedCategories.Any(i=>i.Id==item.Id)?"checked":"")>
                                    @item.CategoryName
                                </label>
                            </div>
                        </div>
                    }
                    <hr />
                    <h4 class="card-title">Blog Durum</h4>
                    <div class="form-group">
                        <div class="form-check">
                            @if (Model.Isapproved == true)
                            {
                                <label asp-for="Isapproved" class="form-check-label">
                                    <input asp-for=Isapproved type="checkbox" checked class="form-check-input">Yayınla
                                </label>
                            }
                            else
                            {
                                <label asp-for="Isapproved" class="form-check-label">
                                    <input asp-for=Isapproved type="checkbox" class="form-check-input">Yayınla
                                </label>

                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</form>
@section Scripts
    {
    <script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('editor');
    </script>
    }

MyBlog/MyBlog.WebUI/Views/Admin/BlogList.cshtml
@using MyBlog.Entities.Concrete;
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IPagedList<Blog>
@{
    ViewData["Title"] = "Blog Liste";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Blog Yazıları</h4>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Resim</th>
                        <th>Başlık</th>
                        <th>Status</th>
                        <th>Yayınlanma Tarihi</th>
                        <th>Düzenle</th>
                        <th>Sil</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var blog in Model)
                    {
                        <tr>
                            <td>@blog.Id</td>
                            <td><img src="~/img/@blog.ImgUrl" style="width:100px;height:100px;"></td>
                            <td width="50px">@blog.Title</td>
                            <td>
                                @if (blog.IsApproved == true)
                                {
                                    <label class="badge badge-gradient-success">Yayında</label>
                                }
                                else if (blog.IsApproved == false)
                                {
                                    <label class="badge badge-gradient-danger">Yayında değil</label>
                                }

                            </td>
                            <td>@blog.CreateDate.ToString("dd MM yyyy")</td>
                            <td><a asp-controller="Admin" asp-action="BlogEdit" asp-route-id="@blog.Id" class="btn btn-success btn-fw">Düzenle</a></td>
                            <td><a class="btn btn-danger btn-fw">Sil</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            @Html.PagedListPager((IPagedList)Model,page=>Url.Action("BlogList",new{page,@class="btn btn-dark btn-fw"}))
            <br />
            <a asp-controller="Admin" asp-action="BlogAdd" class="btn btn-warning btn-fw">Kategori Ekle</a>
        </div>
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/CatAdd.cshtml
@using MyBlogWebUI.Models;
@model CategoryModel
@{
    ViewData["Title"] = "Kategori Ekle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kategori Ekle</h4>
            <form asp-controller="Admin" asp-action="CatAdd" method="post" class="forms-sample">
                <div class="form-group">
                    <label>Kategori Adı</label>
                    <input asp-for=CategoryName type="text" class="form-control" placeholder="Kategori Adı">
                </div>
                <div class="form-group">
                    <label>Kategori Url</label>
                    <input asp-for=Url type="text" class="form-control" placeholder="Kategori Url">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-gradient-warning mr-2">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/CatEdit.cshtml
@using MyBlogWebUI.Models;
@model CategoryModel
@{
    ViewData["Title"] = "Kategori Düzenle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Kategori Düzenle</h4>
                <form asp-controller="Admin" asp-action="CatEdit" method="post" class="forms-sample">
                    <input type="hidden" name="Id" value="@Model.Id">
                    <div class="form-group">
                        <label>Kategori Adı</label>
                        <input asp-for=CategoryName type="text" class="form-control" placeholder="Kategori Adı">
                    </div>
                    <div class="form-group">
                        <label>Kategori Url</label>
                        <input asp-for=Url type="text" class="form-control" placeholder="Kategori Url">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                    </div>

                    <div id="blogs">

                        @for (int i = 0; i < Model.Blogs.Count; i++)
                        {
                            <input type="hidden" name="Products[@i].ProductId" value="@Model.Blogs[@i].Id">
                            <input type="hidden" name="Products[@i].ImageUrl" value="@Model.Blogs[@i].Title">
                        }

                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Blog Yazıları</h4>
                @if (Model.Blogs.Count > 0)
                {
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Başlık</th>
                                <th>Düzenle</th>
                                <th>Sil</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var blog in Model.Blogs)
                            {
                                <tr>
                                    <td>@blog.Id</td>
                                    <td width="50px">@blog.Title</td>
                                    <td><a asp-controller="Admin" asp-action="BlogEdit" asp-route-id="@blog.Id" class="btn btn-success btn-fw">Düzenle</a></td>
                                    <td>
                                        <form asp-controller="Admin" asp-action="DeleteFromCategory" method="post" style="display: inline;">
                                            <input type="hidden" name="blogId" value="@blog.Id">
                                            <input type="hidden" name="categoryId" value="@Model.Id">
                                            <button type="submit" class="btn btn-danger btn-fw">Sil</button>
                                        </form>
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-warning text-dark">
                        <h3>Kategoriye Ait Blog Yok</h3>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/CatList.cshtml
@using MyBlog.Entities.Concrete;
@model List<Category>
@{
    ViewData["Title"] = "Kategori Liste";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Kategoriler</h4>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Kategori Name</th>
                        <th>Url</th>
                        <th>Düzenle</th>
                        <th>Sil</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var cat in Model)
                    {
                        <tr>
                            <td>@cat.Id</td>
                            <td>@cat.CategoryName</td>
                            <td>@cat.Url</td>
                            <td><a asp-controller="Admin" asp-action="CatEdit" asp-route-id="@cat.Id" class="btn btn-success btn-fw">Düzenle</a></td>
                            <td><a class="btn btn-danger btn-fw">Sil</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <br />
            <a asp-controller="Admin" asp-action="CatAdd" class="btn btn-warning btn-fw">Kategori Ekle</a>
        </div>
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/ComEdit.cshtml
@using MyBlog.Entities.Concrete;
@model Comment
@{
    ViewData["Title"] = "Yorum Düzenler ";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Yorum Edit</h4>
            <form asp-controller="Admin" asp-action="ComEdit" method="post" class="forms-sample">
                <input asp-for=Id type="hidden" value="@Model.Id" />

                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Kullanıcı Adı</label>
                        <input asp-for=UserName type="text" class="form-control" readonly>
                </div>
                <div class="form-group row">
                    <label  class="col-sm-3 col-form-label">Email</label>
                        <input asp-for=Mail type="text" class="form-control" readonly>
                </div>
                <div class="form-group row">
                    <label  class="col-sm-3 col-form-label">Yorum</label>
                        <textarea asp-for=Yorum type="text" class="form-control"></textarea>
                </div>
                <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
            </form>
        </div>
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/ComList.cshtml
@using MyBlog.Entities.Concrete;

@model List<Comment>
@{
    ViewData["Title"] = "Yorum Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Yorumlar</h4>

            @if (Model.Count==0)
            {
                 <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-warning">
                                Yorum Bulunamadı 
                            </div>
                        </div>
                    </div>
            }
            else
            {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>User Name</th>
                        <th>Mail</th>
                        <th>Yorum</th>

                        <th>Düzenle</th>
                        <th>Sil</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var com in Model)
                    {
                        <tr>
                            <td>@com.Id</td>
                            <td>@com.UserName</td>
                            <td>@com.Mail</td>
                            <td>@com.Yorum</td>
                            <td><a asp-controller="Admin" asp-action="ComEdit" asp-route-id="@com.Id" class="btn btn-success btn-fw">Düzenle</a></td>
                            <form asp-controller="Admin" asp-action="ComDel" method="post">
                                <input type="hidden" name="Id" value="@com.Id">
                            <td><button type="submit" class="btn btn-danger btn-fw">Sil</button></td>
                            </form>
                        </tr>
                    }
                </tbody>
            </table>
            }
        </div>
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "My Blog Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header mt-5">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-warning text-white mr-2">
            <i class="mdi mdi-home"></i>
        </span> Dashboard
    </h3>
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <span></span>Genel Bakış <i class="mdi mdi-alert-circle-outline icon-sm text-warning align-middle"></i>
            </li>
        </ul>
    </nav>
</div>
<div class="row">
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-danger card-img-holder text-white">
            <div class="card-body">
                <img src="~/writer/assets/images//dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">
                    Toplam Blog Sayısı <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                </h4>
                @await Component.InvokeAsync("BlogCount")
            </div>
        </div>
    </div>
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-info card-img-holder text-white">
            <div class="card-body">
                <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">
                    Yayındaki Blog Sayısı <i class="mdi mdi-bookmark-outline mdi-24px float-right"></i>
                </h4>
                @await Component.InvokeAsync("BlogIsapprovedCount")
            </div>
        </div>
    </div>
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-success card-img-holder text-white">
            <div class="card-body">
                <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">
                    Onay Beklenyen Bloglar <i class="mdi mdi-diamond mdi-24px float-right"></i>
                </h4>
                @await Component.InvokeAsync("BlogIsapprovCount")
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-warning card-img-holder text-white">
            <div class="card-body">
                <img src="~/writer/assets/images//dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">
                    Kategori Sayısı <i class="mdi mdi-chart-line mdi-24px float-right"></i>
                </h4>
                @await Component.InvokeAsync("CategoryCount")
            </div>
        </div>
    </div>
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-dark card-img-holder text-white">
            <div class="card-body">
                <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">
                    Mesaj Sayısı <i class="mdi mdi-bookmark-outline mdi-24px float-right"></i>
                </h4>
                @await Component.InvokeAsync("MessageCount")
            </div>
        </div>
    </div>
    <div class="col-md-4 stretch-card grid-margin">
        <div class="card bg-gradient-primary card-img-holder text-white">
            <div class="card-body">
                <img src="~/writer/assets/images/dashboard/circle.svg" class="card-img-absolute" alt="circle-image" />
                <h4 class="font-weight-normal mb-3">
                    Yorum Sayısı <i class="mdi mdi-diamond mdi-24px float-right"></i>
                </h4>
                @await Component.InvokeAsync("CommentCountList")

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12 grid-margin">
        @await Component.InvokeAsync("AdminBlogList")
    </div>
</div>

MyBlog/MyBlog.WebUI/Views/Admin/MesList.cshtml
@using MyBlog.Entities.Concrete;
@model List<Messages>
@{
    ViewData["Title"] = "Mesaj Listesi";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="col-md-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Mesajlar</h4>
             @if (Model.Count==0)
            {
                 <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-warning">
                                Yorum Bulunamadı 
                            </div>
                        </div>
                    </div>
            }
            else
            {
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>User Name</th>
                        <th>E-Mail</th>
                        <th>Konu</th>
                        <th>Mesaj</th>
                        <th>Mesaj Durum</th>
                        <th>Detay/Cevap</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var mes in Model)
                    {
                        <tr>
                            <td>@mes.Id</td>
                            <td>@mes.Name</td>
                            <td>@mes.Email</td>
                            <td>@mes.Title</td>
                            <td>@mes.Message</td>
                            <td>
                                @if (mes.MessageStatus == true)
                                {
                                    <i class="mdi mdi-checkbox-marked-outline mr-2" aria-hidden="true"></i>
                                }
                                else
                                {
                                    <i class="mdi mdi-checkbox-blank-outline mr-2" aria-hidden="true"></i>
                                }
                            </td>
                            <td><a asp-controller="Admin" asp-action="MesSend" asp-route-id="@mes.Id" class="btn btn-success btn-fw">Cevapla</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            }
        </div>
    </div>
</div>