MyBlog/MyBlog.WebUI/ViewComponents/Admin/AdminNavbarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;

namespace MyBlog.WebUI.ViewComponents.Admin
{
    public class AdminNavbarViewComponent : ViewComponent
    {
        private IAuthorService _authorService;
        public AdminNavbarViewComponent(IAuthorService authorService)
        {
            _authorService = authorService;
        }
        public IViewComponentResult Invoke()
        {
            var entity = _authorService.GetAll().FirstOrDefault();
            return View(entity);
        }
    }
}

MyBlog/MyBlog.WebUI/ViewComponents/Index/FooterTagViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyBlog.Business.Abstract;

namespace MyBlog.WebUI.ViewComponents.Index
{
    public class FooterTagViewComponent : ViewComponent
    {
        private ICategoryService _categoryService;

        public FooterTagViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["category"] != null)
                ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_categoryService.GetAll().Take(6));
        }
    }
}

MyBlog/MyBlog.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> @ViewData["Title"]</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.7.95/css/materialdesignicons.min.css" integrity="sha512-YXUKdb6hkfGORF1hznwemkadkHhFwLUfcW8GBm2IexcCtdn+2shk8IrDT4LOtxN3jXJCSRb28lxEjU05bOQZFA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/writer/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/writer/assets/css/style.css">
    <link rel="shortcut icon" href="~/writer/assets/images/favicon.ico" />
</head>
<body>
    <div class="container-scroller">

        <div class="container-fluid page-body-wrapper">

            @await Component.InvokeAsync("AdminNavbar")
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>

                <footer class="footer">
                    <div class="container-fluid clearfix">
                        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © myblog.com 2023</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">My Blog Admin Panel</span>
                    </div>
                </footer>
            </div>
        </div>
    </div>

    <script src="~/writer/assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/writer/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/writer/assets/js/off-canvas.js"></script>
    <script src="~/writer/assets/js/hoverable-collapse.js"></script>
    <script src="~/writer/assets/js/misc.js"></script>
    <script src="~/writer/assets/js/dashboard.js"></script>
    <script src="~/writer/assets/js/todolist.js"></script>

    @RenderSection("Scripts",false)
</body>
</html>

MyBlog/MyBlog.WebUI/Views/Shared/_MyBlogLayout.cshtml
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Blog</title>
    <link href="~/css/media_query.css" rel="stylesheet" type="text/css" />
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.7.95/css/materialdesignicons.min.css" integrity="sha512-YXUKdb6hkfGORF1hznwemkadkHhFwLUfcW8GBm2IexcCtdn+2shk8IrDT4LOtxN3jXJCSRb28lxEjU05bOQZFA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/css/animate.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="~/css/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="~/css/owl.theme.default.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style_1.css" rel="stylesheet" type="text/css" />
    <script src="~/js/modernizr-3.5.0.min.js"></script>
</head>
<body>
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-3 fh5co_padding_menu">
                    <img src="~/img/MyBlogLogo.png"  alt="img" class="fh5co_logo_width" />
                </div>
                <div class="col-12 col-md-9 align-self-center fh5co_mediya_right">
                    <div class="text-center d-inline-block">
                        <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-search"></i></div></a>
                    </div>
                    <div class="text-center d-inline-block">
                        <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-linkedin"></i></div></a>
                    </div>
                    <div class="text-center d-inline-block">
                        <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-google-plus"></i></div></a>
                    </div>
                    <div class="text-center d-inline-block">
                        <a href="https://twitter.com/fh5co" target="_blank" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-twitter"></i></div></a>
                    </div>
                    <div class="text-center d-inline-block">
                        <a href="https://fb.com/fh5co" target="_blank" class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-facebook"></i></div></a>
                    </div>

                    <div class="d-inline-block text-center dd_position_relative ">
                        <select class="form-control fh5co_text_select_option">
                            <option>English </option>
                            <option>French </option>
                            <option>German </option>
                            <option>Spanish </option>
                        </select>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-faded fh5co_padd_mediya padding_786">
        <div class="container padding_786">
            @await Html.PartialAsync("_navbar")
        </div>
    </div>


    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="container-fluid fh5co_footer_bg pb-3">
        <div class="container animate-box">
            <div class="row">
                <div class="col-12 spdp_right py-5"><img src="~/img/MyBlogLogoWhite.png" alt="img" class="footer_logo" /></div>
                <div class="clearfix"></div>
                <div class="col-md-4">
                    <div class="footer_main_title py-3">Hakkımda</div>
                    <div class="footer_sub_about pb-3">
                        Merhaba, Ömer Faruk Gül. Bu blogda sizlere ASP.NET üzerindeki deneyimlerimi ve teknik bilgilerimi paylaşmak için buradayım. Web geliştirme konusunda tutkulu birisi olarak, ASP.NET'in gücünü ve esnekliğini keşfetmek benim için büyük bir zevk.
                    </div>
                    <div class="footer_mediya_icon">
                        <div class="text-center d-inline-block">
                            <a class="fh5co_display_table_footer">
                                <div class="fh5co_verticle_middle"><i class="fa fa-linkedin"></i></div>
                            </a>
                        </div>
                        <div class="text-center d-inline-block">
                            <a class="fh5co_display_table_footer">
                                <div class="fh5co_verticle_middle"><i class="fa fa-google-plus"></i></div>
                            </a>
                        </div>
                        <div class="text-center d-inline-block">
                            <a class="fh5co_display_table_footer">
                                <div class="fh5co_verticle_middle"><i class="fa fa-twitter"></i></div>
                            </a>
                        </div>
                        <div class="text-center d-inline-block">
                            <a class="fh5co_display_table_footer">
                                <div class="fh5co_verticle_middle"><i class="fa fa-facebook"></i></div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="footer_main_title py-3">Kategori</div>
                    <ul class="footer_menu">
                        @await Component.InvokeAsync("FooterTag")
                    </ul>
                </div>
                <div class="col-md-4 ">
                    <div class="footer_main_title py-3">Yeni Bloglar</div>
                    @await Component.InvokeAsync("LastContentImg")
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid fh5co_footer_right_reserved">
        <div class="container">
            <div class="row  ">
                <div class="col-12 col-md-6 py-4 Reserved mt-3"> © Copyright 2023, Tüm Hakları Saklıdır.</div>
                <div class="col-12 col-md-6 spdp_right py-4">
                    @await Html.PartialAsync("_footerNavbar")
                </div>
            </div>
        </div>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    @RenderSection("scripts",required:false)
    <script src="~/js/main.js"></script>
    
</body>
</html>

MyBlog/MyBlog.WebUI/Views/Shared/_footerNavbar.cshtml
<style>
    .navbar-nav .nav-link {
        color: #222 !important;
        padding-top: 12px !important;
        padding-bottom: 15px !important;
        padding-left: 20px !important;
        padding-right: 20px !important;
        margin: 0 20px !important;
        -moz-transition: all .5s ease;
        -o-transition: all .5s ease;
        -webkit-transition: all .5s ease;
        -ms-transition: all .5s ease;
        transition: all .5s ease;
        position: relative !important;
    }
</style>

<nav class="navbar navbar-toggleable-md">
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Ansayfa <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Home" asp-action="BlogList">Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Home" asp-action="About">Hakkımda <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Home" asp-action="Contact">İletişim <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

MyBlog/MyBlog.WebUI/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-toggleable-md navbar-light ">
    <button class="navbar-toggler navbar-toggler-right mt-3" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="fa fa-bars"></span>
    </button>
    <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="img/logo.png" alt="img" class="mobile_logo_width" /></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Ansayfa <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Home" asp-action="BlogList">Blog <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Home" asp-action="About">Hakkımda <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" asp-controller="Home" asp-action="Contact">İletişim <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>